I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 54, in script
    $ talkedto = [normantalkedto, miketalkedto, kesslertalkedto, scotttalkedto, liztalkedto, julietalkedto, javiertalkedto, rileytalkedto]
  File "game/script.rpy", line 54, in <module>
    $ talkedto = [normantalkedto, miketalkedto, kesslertalkedto, scotttalkedto, liztalkedto, julietalkedto, javiertalkedto, rileytalkedto]
NameError: name 'rileytalkedto' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 54, in script
    $ talkedto = [normantalkedto, miketalkedto, kesslertalkedto, scotttalkedto, liztalkedto, julietalkedto, javiertalkedto, rileytalkedto]
  File "C:\Users\acer\Desktop\folder\renpy-6.99.12.4-sdk\renpy\ast.py", line 862, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\acer\Desktop\folder\renpy-6.99.12.4-sdk\renpy\python.py", line 1888, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 54, in <module>
    $ talkedto = [normantalkedto, miketalkedto, kesslertalkedto, scotttalkedto, liztalkedto, julietalkedto, javiertalkedto, rileytalkedto]
NameError: name 'rileytalkedto' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.14.3.3347
Coyote Creek 1.0
Sat Jun 09 00:45:58 2018
